services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - BASE_URL=http://localhost:8080
      - PASSWORD_SALT=salt
      - JWT_SECRET=secret
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - images:/.images
      - webp:/.webp
      - og-png:/.og-png
      - .:/opt/project
    depends_on:
      - db
    network_mode: host

  webp-proccess:
    image: alpine:3.18
    volumes:
      - webp:/app/output
      - ./scripts/urls.txt:/app/urls.txt
      - ./scripts/webp-script.sh:/app/script.sh
    working_dir: /app
    entrypoint: sh
    command: script.sh


volumes:
  postgres_data:
  images:
  webp:
  og-png:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/wf/Projects/IdeaProjects/ecommerce-faster/htmx-faster/.png-og
